routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();


Route::group(['prefix' => '/', 'middleware' => 'auth'], function () {
    Route::get('/', function () {
        //return view('welcome');
        return redirect()->route("home");
    });

    Route::get('/home', 'HomeController@index')->name('home');

    Route::resource('product', 'ProductController');
    Route::get('product/images/{id}', 'ProductController@images')->name('product.images');
    Route::get('product/feature/{id}/{product_id}', 'ProductController@feature')->name('product.feature');
    Route::resource('category', 'CategoryController');
});

resources/views/category.blade.php
@extends('layouts.app')

@section('content')
    <div class="container-fluid">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">Category</div>

                    <div class="card-body">
                        @if (session('status'))
                            <div class="alert alert-success" role="alert">
                                {{ session('status') }}
                            </div>
                        @endif

                        @if(\Session::has('success'))
                            <div class="alert alert-success">
                                {{\Session::get('success')}}
                            </div>
                        @endif

                        <div class="row">
                            <div class="col-md-3">
                                <a class="btn btn-primary"
                                   href="{{ route('category.create') }}">{{ __('Add Category') }}</a>
                            </div>
                            <div class="col-md-5">
                                <form action="{{route('category.index')}}" class="d-flex">
                                    <input name="search" class="form-control mr-2" type="text" value="{{$search}}">
                                    <button class="btn btn-primary" type="submit">Filter</button>
                                </form>
                            </div>
                        </div>


                        <hr/>

                        <table class="table table-striped table-bordered table-responsive">
                            <thead>
                            <tr>
                                <td>Image</td>
                                <td>Name</td>
                                <td>Added</td>
                                <td>Modified</td>
                                <td>Order</td>
                                <td>Status</td>
                                <td>No. of products</td>
                                <td colspan="2">Action</td>
                            </tr>
                            </thead>
                            <tbody>
                            @forelse($category as $cate)
                                <tr>
                                    <td>
                                        <img src="{{url('uploads/category/'.$cate->image_name)}}" width="50" height="50"
                                             alt="{{$cate->name}}"/>
                                    </td>
                                    <td>{{$cate->name}}</td>
                                    <td>{{$cate->created_at}}</td>
                                    <td>{{$cate->updated_at}}</td>
                                    <td>{{$cate->order}}</td>
                                    <td>{{$cate->status == 1 ? "Yes" : "No" }}</td>
                                    <td>{{"0"}}</td>
                                    <td><a href="{{route('category.edit',$cate->id)}}" class="btn btn-primary">Edit</a>
                                    </td>
                                    <td>
                                        <form action="{{route('category.destroy', $cate->id)}}" method="post">
                                            {{csrf_field()}}
                                            <input name="_method" type="hidden" value="DELETE">
                                            <button class="btn btn-danger" type="submit">Delete</button>
                                        </form>
                                    </td>
                                </tr>
                            @empty
                                <tr>
                                    <td colspan="7" class="text-center"><p>No data found!</p></td>
                                </tr>
                            @endforelse
                            </tbody>
                        </table>

                        <div class="text-center">
                            {{ $category->links() }}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container-fluid">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/product.blade.php
@extends('layouts.app')

@section('content')
    <div class="container-fluid">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">Product</div>

                    <div class="card-body">
                        @if (session('status'))
                            <div class="alert alert-success" role="alert">
                                {{ session('status') }}
                            </div>
                        @endif

                        @if(\Session::has('success'))
                            <div class="alert alert-success">
                                {{\Session::get('success')}}
                            </div>
                        @endif

                        <a class="btn btn-primary" href="{{ route('product.create') }}">{{ __('Add Product') }}</a>

                        <hr/>

                        <table class="table table-striped table-bordered table-responsive">
                            <thead>
                            <tr>
                                <td>#</td>
                                <td>id</td>
                                <td>Name</td>
                                <td>product_code</td>
                                <td>quantity</td>
                                <td>price</td>
                                <td>sale_price</td>
                                <td>category_id</td>
                                <td>order</td>
                                <td>status</td>
                                <td colspan="3">Action</td>
                            </tr>
                            </thead>
                            <tbody>

                            @forelse($product as $pro)
                                <tr>
                                     <td>
                                         <img src="{{url('uploads/product/'. \App\ProductImage::where('is_feature',1)->where('product_id', $pro->id)->get()->pluck('product_image')->implode('') )}}" width="50" height="50"
                                              alt="{{$pro->name}}"/>
                                     </td>
                                    <td>{{$pro->id}}</td>
                                    <td>{{$pro->name}}</td>
                                    <td>{{$pro->product_code}}</td>
                                    <td>{{$pro->quantity}}</td>
                                    <td>{{$pro->price}}</td>
                                    <td>{{$pro->sale_price}}</td>
                                    <td>
                                        @forelse($pro->category_id as $cat)
                                            {{ \App\Category::where('id','=',$cat)->get()->pluck('name')->implode('') }},
                                        @empty
                                            {{"--"}}
                                        @endforelse
                                    </td>
                                    <td>{{$pro->order}}</td>
                                    <td>{{$pro->status == 1 ? "Yes" : "No" }}</td>
                                    <td><a href="{{route('product.edit',$pro->id)}}" class="btn btn-primary">Edit</a>
                                    </td>
                                    <td>
                                        <form action="{{route('product.destroy', $pro->id)}}" method="post">
                                            {{csrf_field()}}
                                            <input name="_method" type="hidden" value="DELETE">
                                            <button class="btn btn-danger" type="submit">Delete</button>
                                        </form>
                                    </td>
                                    <td><a href="{{route('product.images',$pro->id)}}" class="btn btn-primary">Images</a>
                                </tr>
                            @empty
                                <tr>
                                    <td colspan="10" class="text-center"><p>No data found!</p></td>
                                </tr>
                            @endforelse
                            </tbody>
                        </table>

                        <div class="text-center">
                            {{ $product->links() }}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection