routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();


Route::group(['prefix' => '/', 'middleware' => 'auth'], function () {
    Route::get('/', function () {
        //return view('welcome');
        return redirect()->route("home");
    });

    Route::get('/home', 'HomeController@index')->name('home');

    Route::resource('product', 'ProductController');
    Route::get('product/images/{id}', 'ProductController@images')->name('product.images');
    Route::get('product/feature/{id}/{product_id}', 'ProductController@feature')->name('product.feature');
    Route::resource('category', 'CategoryController');
});

app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    const Product_STATUS = 1;
    const Product_INIT_ORDER = 0;

    protected $table = "products";
    protected $fillable = [
        'name', 'product_code', 'quantity', 'price', 'sale_price', 'category_id', 'order', 'status'
    ];

    public function generateProductCode($number)
    {
        $sessPrefix = rand(100, 300);
        $sess = $sessPrefix.$number.time();
        $sess = substr($sess, -20);

        return $sess;
    }

   /* public function category() {
        return $this->belongsTo("App\Category");
    }*/

    public function productImages() {
        return $this->hasMany("App\ProductImage");
    }

    public function getCategoryIdAttribute($value) {
        return explode(",", $value);
    }
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use App\Category;
use App\Product;
use App\ProductImage;
use Illuminate\Http\Request;

class ProductController extends Controller
{
    public function index()
    {
        $product = Product::latest()->orderBy('id', 'desc')->paginate(10);

        return view('product', compact('product'))
            ->with('i', (request()->input('page', 1) - 1) * 5);
    }

    public function images($id)
    {
        $images = ProductImage::where('product_id', $id)->get();

        return view('product.images', compact('images'));
    }

    public function feature($id, $product_id)
    {
       ProductImage::where('product_id', $product_id)->update(['is_feature' => 0]);
       ProductImage::where('id', $id)->update(['is_feature' => 1]);

        return redirect()->route('product.index');
    }

    public function create()
    {
        $category = Category::select('id', 'name')->get();

        return view('product.create', compact('category'));
    }

    public function store(Request $request)
    {
        request()->validate([
            'pro_name' => 'required',
            //'product_code' => 'required',
            'quantity' => 'required',
            'price' => 'required',
            'sale_price' => 'required',
            'category_id' => 'required',
            'product_images' => 'required',
            'pro_status' => 'required',
        ]);

        $product = new Product();
        $product->name = $request->pro_name;
        $product->product_code = $product->generateProductCode(10);
        $product->quantity = $request->quantity;
        $product->price = $request->price;
        $product->sale_price = $request->sale_price;
        $product->category_id = is_array($request->category_id) ? implode(',',
            $request->category_id) : $request->category_id;
        $product->order = Product::Product_INIT_ORDER;
        $product->status = $request->pro_status;
        $product->save();

        if ($request->hasFile('product_images')) {
            $productId = $product->id;
            foreach ($request->file('product_images') as $file) {
                $extension = $file->getClientOriginalExtension();
                if (in_array($extension, ['jpeg', 'png'])) {
                    $new_name = rand().time().'_'.$productId.'.'.$extension;
                    $file->move(public_path('uploads/product'), $new_name);

                    ProductImage::create([
                        'product_image' => $new_name,
                        'product_id' => $productId,
                        'is_feature' => 0
                    ]);
                }
            }
        }

        return redirect()->route('product.index')
            ->with('success', 'Product created successfully');
    }

    public function show($id)
    {
        //
    }

    public function edit($id)
    {
        $product = Product::find($id);
        $category = Category::select('id', 'name')->get();

        return view('product.edit', compact(['product','category']));
    }

    public function update(Request $request, $id)
    {
        $productImage = $request->file('image_name');

        if ($productImage != "") {
            request()->validate([
                'pro_name' => 'required',
                //'product_code' => 'required',
                'quantity' => 'required',
                'price' => 'required',
                'sale_price' => 'required',
                'category_id' => 'required',
                'product_images' => 'required',
                'pro_status' => 'required',
            ]);
        } else {
            request()->validate([
                'pro_name' => 'required',
                //'product_code' => 'required',
                'quantity' => 'required',
                'price' => 'required',
                'sale_price' => 'required',
                'category_id' => 'required',
                'pro_status' => 'required',
            ]);
        }

        $product = Product::find($id);
        $product->name = $request->pro_name;
        $product->product_code = $product->generateProductCode(10);
        $product->quantity = $request->quantity;
        $product->price = $request->price;
        $product->sale_price = $request->sale_price;
        $product->category_id = is_array($request->category_id) ? implode(',',
            $request->category_id) : $request->category_id;
        $product->order = Product::Product_INIT_ORDER;
        $product->status = $request->pro_status;
        $product->save();

        if ($request->hasFile('product_images')) {
            foreach ($request->file('product_images') as $file) {
                $extension = $file->getClientOriginalExtension();
                if (in_array($extension, ['jpeg', 'png'])) {
                    $new_name = rand().time().'_'.$id.'.'.$extension;
                    $file->move(public_path('uploads/product'), $new_name);

                    ProductImage::create([
                        'product_image' => $new_name,
                        'product_id' => $id,
                        'is_feature' => 0
                    ]);
                }
            }
        }

        return redirect()->route('product.index')
            ->with('success', 'Product updated successfully');
    }

    public function destroy($id)
    {
        $product = Product::find($id);
        $product->productImages()->delete();
        $product->delete();

        return redirect()->route('product.index')
            ->with('success', 'Product deleted successfully');
    }
}

resources/views/product/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container-fluid">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">Product</div>

                    <div class="card-body">
                        @if (session('status'))
                            <div class="alert alert-success" role="alert">
                                {{ session('status') }}
                            </div>
                        @endif

                        @if ($errors->any())
                            <div class="alert alert-danger">
                                <ul>
                                    @foreach ($errors->all() as $error)
                                        <li>{{ $error }}</li>
                                    @endforeach
                                </ul>
                            </div><br/>
                        @endif
                        <form method="post" action="{{ route('product.store') }}" enctype="multipart/form-data">

                            <input type="hidden" value="{{csrf_token()}}" name="_token"/>

                            <div class="form-group">
                                <label for="image">Category:</label>
                                <select class="form-control" name="category_id[]" multiple>
                                    @foreach($category as $cate)
                                        <option value="{{$cate->id}}">{{$cate->name}}</option>
                                    @endforeach
                                </select>
                            </div>

                            <div class="form-group">
                                <label for="title">Name:</label>
                                <input type="text" class="form-control" name="pro_name"/>
                            </div>

                            <div class="form-group">
                                <label for="title">Quantity:</label>
                                <input type="number" min="0" class="form-control" name="quantity"/>
                            </div>

                            <div class="form-group">
                                <label for="title">price:</label>
                                <input type="number" min="0" class="form-control" name="price"/>
                            </div>

                            <div class="form-group">
                                <label for="title">sale_price:</label>
                                <input type="number" min="0" class="form-control" name="sale_price"/>
                            </div>

                            <div class="form-group">
                                <label for="image">Image:</label>
                                <input name="product_images[]" type="file" accept="image/jpeg, image/png" multiple/>
                            </div>

                            <div class="form-group">
                                <label for="image">Status:</label>
                                <select class="form-control" name="pro_status">
                                    <option value="1">Yes</option>
                                    <option value="0">No</option>
                                </select>
                            </div>

                            <button type="submit" class="btn btn-primary">Create</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/product/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container-fluid">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">Product</div>

                    <div class="card-body">
                        @if (session('status'))
                            <div class="alert alert-success" role="alert">
                                {{ session('status') }}
                            </div>
                        @endif

                        @if ($errors->any())
                            <div class="alert alert-danger">
                                <ul>
                                    @foreach ($errors->all() as $error)
                                        <li>{{ $error }}</li>
                                    @endforeach
                                </ul>
                            </div><br/>
                        @endif
                        <form method="post" action="{{route('product.update', $product->id)}}"
                              enctype="multipart/form-data">
                            {{csrf_field()}}
                            <input name="_method" type="hidden" value="PATCH">

                            <div class="form-group">
                                <label for="image">Category:</label>

                                <select class="form-control" name="category_id[]" multiple>
                                    @foreach($category as $cate)
                                        <option
                                            value="{{$cate->id}}"
                                            selected="{{
                                                in_array($cate->id, $product->category_id) ? "selected" : ""
                                            }}"
                                        >
                                            {{$cate->name}}
                                        </option>
                                    @endforeach
                                </select>
                            </div>

                            <div class="form-group">
                                <label for="title">Name:</label>
                                <input type="text" class="form-control" name="pro_name" value="{{$product->name}}"/>
                            </div>

                            <div class="form-group">
                                <label for="title">Quantity:</label>
                                <input type="number" min="0" class="form-control" name="quantity"
                                       value="{{$product->quantity}}"/>
                            </div>

                            <div class="form-group">
                                <label for="title">price:</label>
                                <input type="number" min="0" class="form-control" name="price"
                                       value="{{$product->price}}"/>
                            </div>

                            <div class="form-group">
                                <label for="title">sale_price:</label>
                                <input type="number" min="0" class="form-control" name="sale_price"
                                       value="{{$product->sale_price}}"/>
                            </div>

                            <div class="form-group">
                                <label for="image">Image:</label>
                                <input name="product_images[]" type="file" accept="image/jpeg, image/png" multiple/>
                            </div>

                            <div class="form-group">
                                <label for="image">Status:</label>
                                <select class="form-control" name="pro_status">
                                    <option value="1" {{$product->status == 1 ? "selected" : ""}}>Yes</option>
                                    <option value="0" {{$product->status == 0 ? "selected" : ""}}>No</option>
                                </select>
                            </div>

                            <button type="submit" class="btn btn-primary">Create</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/product/images.blade.php
@extends('layouts.app')

@section('content')
    <div class="container-fluid">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">Product</div>

                    <div class="card-body">
                        @if (session('status'))
                            <div class="alert alert-success" role="alert">
                                {{ session('status') }}
                            </div>
                        @endif

                        @if ($errors->any())
                            <div class="alert alert-danger">
                                <ul>
                                    @foreach ($errors->all() as $error)
                                        <li>{{ $error }}</li>
                                    @endforeach
                                </ul>
                            </div><br/>
                        @endif
                        <div class="row">
                            @foreach($images as $img)
                                <div class="col-md-3">
                                    <a href="{{ route('product.feature',[$img->id, $img->product_id] ) }}">
                                        <img src="{{url('uploads/product/'.$img->product_image)}}" class="img-rounded"
                                             alt="{{$img->product_image}}" width="100" height="100"/>
                                        <div class="caption">
                                            <p>Is Feature image : {{$img->is_feature === 0 ? "No" : "Yes" }}</p>
                                        </div>
                                    </a>
                                </div>
                            @endforeach
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection