routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();


Route::group(['prefix' => '/', 'middleware' => 'auth'], function () {
    Route::get('/', function () {
        //return view('welcome');
        return redirect()->route("home");
    });

    Route::get('/home', 'HomeController@index')->name('home');

    Route::resource('product', 'ProductController');
    Route::get('product/images/{id}', 'ProductController@images')->name('product.images');
    Route::get('product/feature/{id}/{product_id}', 'ProductController@feature')->name('product.feature');
    Route::resource('category', 'CategoryController');
});

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    const Cat_STATUS = 1;
    const Cat_INIT_ORDER = 0;

    protected $table = "categories";
    protected $fillable = [
        'name','image_name','order','status'
    ];
/*
    public function product() {
        return $this->hasMany("App\Product");
    }*/
}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use App\Category;
use Illuminate\Http\Request;

class CategoryController extends Controller
{
    public function index(Request $request)
    {
        $search = $request->query('search');

        if (!empty($search)) {
            $category = Category::where('name', 'like', '%'.$search.'%')->orderBy('id', 'desc')->paginate(10);
        } else {
            $category = Category::latest()->orderBy('id', 'desc')->paginate(10);
        }

        return view('category', compact(['category', 'search']))
            ->with('i', (request()->input('page', 1) - 1) * 5);
    }

    public function create()
    {
        return view('category.create');
    }

    public function store(Request $request)
    {
        request()->validate([
            'cat_name' => 'required',
            'image_name' => 'required|image|mimes:jpeg,png',
            'cat_status' => 'required',
        ]);

        $category = new Category();
        if ($request->hasFile('image_name')) {
            $categoryImage = $request->file('image_name');
            $extension = $categoryImage->getClientOriginalExtension();

            $new_name = rand().time().'.'.$extension;
            $categoryImage->move(public_path('uploads/category'), $new_name);

            $category->image_name = $new_name;
        }
        $category->name = $request->cat_name;
        $category->order = Category::Cat_INIT_ORDER;
        $category->status = $request->cat_status;
        $category->save();

        return redirect()->route('category.index')
            ->with('success', 'Category created successfully');
    }

    public function show($id)
    {
        //
    }

    public function edit($id)
    {
        $category = Category::find($id);

        return view('category.edit', compact('category'));
    }

    public function update(Request $request, $id)
    {
        $categoryImage = $request->file('image_name');

        if ($categoryImage != "") {
            request()->validate([
                'cat_name' => 'required',
                'cat_status' => 'required',
                'image_name' => 'image|mimes:jpeg,png',
            ]);
        } else {
            request()->validate([
                'cat_name' => 'required',
                'cat_status' => 'required',
            ]);
        }

        $category = Category::find($id);

        if ($request->hasFile('image_name')) {
            $extension = $categoryImage->getClientOriginalExtension();

            $new_name = rand().time().'.'.$extension;
            $categoryImage->move(public_path('uploads/category'), $new_name);

            $category->image_name = $new_name;
        }
        $category->name = $request->cat_name;
        $category->order = Category::Cat_INIT_ORDER;
        $category->status = $request->cat_status;
        $category->save();

        return redirect()->route('category.index')
            ->with('success', 'Category updated successfully');
    }

    public function destroy($id)
    {
        Category::find($id)->delete();

        return redirect()->route('category.index')
            ->with('success', 'Category deleted successfully');
    }
}

resources/views/category/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container-fluid">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">Category</div>

                    <div class="card-body">
                        @if (session('status'))
                            <div class="alert alert-success" role="alert">
                                {{ session('status') }}
                            </div>
                        @endif

                        @if ($errors->any())
                            <div class="alert alert-danger">
                                <ul>
                                    @foreach ($errors->all() as $error)
                                        <li>{{ $error }}</li>
                                    @endforeach
                                </ul>
                            </div><br/>
                        @endif
                        <form method="post" action="{{ route('category.store') }}" enctype="multipart/form-data">

                            <input type="hidden" value="{{csrf_token()}}" name="_token"/>

                            <div class="form-group">
                                <label for="title">Name:</label>
                                <input type="text" class="form-control" name="cat_name"/>
                            </div>

                            <div class="form-group">
                                <label for="image">Image:</label>
                                <input name="image_name" type="file" accept="image/jpeg, image/png"/>
                            </div>

                            <div class="form-group">
                                <label for="image">Status:</label>
                                <select class="form-control" name="cat_status">
                                    <option value="1">Yes</option>
                                    <option value="0">No</option>
                                </select>
                            </div>

                            <button type="submit" class="btn btn-primary">Create</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/category/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container-fluid">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">Category</div>

                    <div class="card-body">
                        @if (session('status'))
                            <div class="alert alert-success" role="alert">
                                {{ session('status') }}
                            </div>
                        @endif

                        @if ($errors->any())
                            <div class="alert alert-danger">
                                <ul>
                                    @foreach ($errors->all() as $error)
                                        <li>{{ $error }}</li>
                                    @endforeach
                                </ul>
                            </div><br/>
                        @endif
                        <form method="post" action="{{route('category.update', $category->id)}}"
                              enctype="multipart/form-data">
                            {{csrf_field()}}
                            <input name="_method" type="hidden" value="PATCH">

                            <div class="form-group">
                                <label for="url">Name:</label>
                                <input cols="5" rows="5" class="form-control" name="cat_name"
                                       value="{{$category->name}}"/>
                            </div>

                            <div class="form-group">
                                <label for="image">Image:</label>
                                <input name="image_name" type="file" accept="image/jpeg, image/png"/>
                            </div>

                            <div class="form-group">
                                <label for="image">Status:</label>
                                <select class="form-control" name="cat_status">
                                    <option value="1" {{$category->status == 1 ? "selected" : ""}}>Yes</option>
                                    <option value="0" {{$category->status == 0 ? "selected" : ""}}>No</option>
                                </select>
                            </div>

                            <button type="submit" class="btn btn-primary">Update</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection